# Generated by Django 5.0.1 on 2024-01-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='house',
            name='slug',
            field=models.SlugField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suburb',
            name='slug',
            field=models.SlugField(default=' ', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='town',
            name='slug',
            field=models.SlugField(default='-', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='slugfield', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='suburb',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
